### ISSUE TITLE
Missing Dispenser Interaction for suspicious snowballs

### ISSUE THREAD

**Issue by thelegitdolt** [LudoCrypt/Sussy-Balls#3]
### Describe the Bug

In vanilla, all projectiles (like arrows, fire charges, eggs, tipped arrows, whatever) can be shot out of a dispenser. However, this currently does not apply to the suspicious snowballs.

### Mod Version

1.0.1

### Minecraft Version

1.19.2

### Loader

Forge

**Comment by LudoCrypt** [comment]
Strange, Ill look into this!

**Comment by LudoCrypt** [comment]
Fixed in 1.0.2
